import React from 'react'
import { createRoot } from 'react-dom/client'
import '@fontsource/mukta/400.css'
import '@fontsource/mukta/500.css'
import '@fontsource/mukta/700.css'
import '@fontsource/tiro-devanagari-hindi/400.css'
import '@fontsource/noto-sans/400.css'
import './index.css'
import App from './App.jsx'
createRoot(document.getElementById('root')).render(<App />)
